# Scrape CSD and curate the synonyms
NOTE: you need a CSD licence to install and use the CSD API

In [1]:
from pathlib import Path
from tqdm import tqdm
import pandas as pd

In [3]:
import ccdc
import ccdc.io
import ccdc.search
print("ccdc.__version__", ccdc.__version__)
print("ccdc.io.csd_directory()", ccdc.io.csd_directory())
print("ccdc.io.csd_version()", ccdc.io.csd_version())

subset_mofs_all = Path(ccdc.io.csd_directory()) / "subsets" / "CSD_MOF_subsets" / "MOF_subset.gcd"
print(f"Number of MOFs: {len(ccdc.io.EntryReader(str(subset_mofs_all)))}")

ccdc.__version__ 3.6.1
ccdc.io.csd_directory() C:/Users/james/CCDC/ccdc-data/csd
ccdc.io.csd_version() 601
Number of MOFs: 135253

In [4]:
n_entries = len(ccdc.io.EntryReader(str(subset_mofs_all)))
rows = [{} for _ in range(n_entries)] # Pre allocate for speed
for i, entry in enumerate(tqdm(ccdc.io.EntryReader(str(subset_mofs_all)))): # Takes 2 minutes
    for col in ['identifier', 'ccdc_number','formula', 'has_disorder']:
        rows[i][col] = getattr(entry, col)
    rows[i]['publication_year'] = entry.publication.year
    doi = entry.publication.doi
    if doi: # can be None
        doi = doi.lower() # Lower caption to improve match in a later step
    rows[i]['publication_doi'] = doi 
    synonyms = list(entry.synonyms)
    rows[i]['synonyms_orig'] = synonyms
df = pd.DataFrame(rows) 

df.to_csv("data/step-00.csv", index=False) 
# step-00.csv contains all CSD entries of MOF subset: id, formula, has_disorder, pub year, doi, synonyms_orig

100%|██████████| 135253/135253 [09:17<00:00, 242.68it/s]

In [6]:
df.head(3)

,identifier,ccdc_number,formula,has_disorder,publication_year,publication_doi,synonyms_orig
0,ABACUF,1100034,(C6 H14 Ba2 Cu1 O16)n,False,1958,None,[]
1,ABACUF01,230290,(C6 H14 Ba2 Cu1 O16)n,False,2004,10.1016/j.molstruc.2004.03.051,[]
2,ABADUG,2104232,"2(C51 H30 N2 O9 Zn2)n,(C51 H30 N2 O9 Zn2)n",True,2021,None,[]

In [7]:
df = pd.read_csv("data/step-00.csv")
print("CSD entries having synonyms:", len(df[df['synonyms_orig']!="[]"]))

CSD entries having synonyms: 12922

In [8]:
# Correct the names from "synonyms_orig", and create a new column "synonyms": exclude misleading ones, and solvents/adsorbate.
# NOTE: the reason why I'm doing it here and not later in the name match, is to exclude those names that are obviously problematic,
#       and I want to remove completely, to make later checks easier.

ADSORBATES_LIST = [
    "carbon", # carbon dioxide
    "deuteromethane",
    "methane",
    "ethane",
    "ethene",
    "dinitrogen",
    "acetylene",
    "acetylene",
    "acetaldehyde",
    "ethylamine"  
]

df = pd.read_csv("data/step-00.csv")
df['synonyms'] = None # create new column for .at
for i, synonyms in enumerate(tqdm(df['synonyms_orig'])):
    synonyms_valid = [] 
    for name in eval(synonyms): #there may be more than one synonym, but it is not very frequent
        # Exclude some fake names:
        if any([
            name.startswith('catena'),
            name.startswith('Teaching Subset'),
            name.startswith('DrugBank')
            #len(name)>20
        ]):
            continue
            
        if name in ["","MOF-1", "MOF-2", 1, 2, "1", "2"]:
            continue
            
        name_split = name.split(" ")
        if len(name_split)>1 and name_split[1] in ADSORBATES_LIST: # remove adsorbent from name
            name = name_split[0] 
            
        synonyms_valid.append(name)
        
    df.at[i,'synonyms'] = synonyms_valid

df.to_csv("data/step-01.csv", index=False) 
# step-01.csv: add "synonyms" column with corrected CSD syns

100%|██████████| 135253/135253 [00:04<00:00, 27065.67it/s]

In [9]:
df = pd.read_csv("data/step-01.csv")
print("CSD entries having valid synonyms:", len(df[df['synonyms']!="[]"]))

CSD entries having valid synonyms: 9410

In [10]:
df = pd.read_csv("data/step-01.csv")
df[df['synonyms']!="[]"].head(3)

,identifier,ccdc_number,formula,has_disorder,publication_year,publication_doi,synonyms_orig,synonyms
13,ABAVIM01,1984147,"(C24 H26 N3 Ni1 O11 P3)n,H2 O1",True,2021,10.1007/s12274-020-3056-6,['IEF-13'],['IEF-13']
37,ABECIX,2081306,(C52 H34 Ag1 Co3 F1 N2 O13 P2)n,True,2021,10.1021/jacs.1c05564,['Ag-PCM-102'],['Ag-PCM-102']
38,ABECOD,2081307,"0.71(C55 H43 Ag1 Co3 F1 N3 O15 P2)n,0.29(C55 H...",True,2021,10.1021/jacs.1c05564,['AgCu-PCM-102'],['AgCu-PCM-102']

In [11]:
# Inspect names that have a space: one can see that many more can be fixed but it is hard to find general rules
df = pd.read_csv("data/step-01.csv")
for i in df.index:
    synonyms = eval(df.at[i,'synonyms'])
    if len(synonyms)>0:
        first = synonyms[0]
        if len(first.split(" "))>1:
            print(first)

C32 H42 O20 S4 Zn4
MAF-40 unknown solvate
CSUST-4 N,N-dimethylformamide solvate
di-ammonium catena-(diuranyl trioxalate)
MFM-303(Al) ammonia
MFM-303(Al) hydrate
Anhydrous sodium naproxen
IRH-5-as synthesised
IRH-4-as synthesised
amoxicillin sodium
amoxicillin sodium methyl acetate solvate
copper-doped UiO-66 unknown solvate
UiO-66 unknown solvate
EMOF 1
ZUL-330 /  ZUL-430 acetylene
ZUL-430 activated
ZUL-330 activated
IHEP-17 unknown solvate
IHEP-17-I unknown solvate
IHEP-18 unknown solvate
Sodium Acetate
Sodium Acetate
Sodium acetate
ZUL-C5 2,2-dimethylbutane
ZUL-C5 n-hexane solvate
ZUL-C5 hemikis(3-methylpentane)
Strontium Manganese Trifluoroacetate
activated NTU-101-NH2
activated NTU-101
MIL-100 (Al)
NU-400 MOF
Uranyl phenylphosphinate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 octadecahydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hexadecahydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-303 hydrate
MOF-333 hydrate
NKU-128 toluene unknown solvate
NKU-128 dimethyl sulfoxide unknown solvate
NKU-128 N,N-dimethylformamide unknown solvate
NKU-128 tetrahydrofuran unknown solvate
NKU-128 unknown solvate
NKU-128 unknown solvate
NKU-128 unknown solvate
NKU-128 unknown solvate
NKU-128 cyclohexane unknown solvate
Hexa-aqua-nickel(ii) dipotassium tetrahydrogen tetra-o-phthalate tetrahydrate
NTU-85-F bis(propylene) clathrate
NTU-85-F bis(propane) clathrate
NJU-Bai 14
ZIF-78-Co activated
ZIF-79-Co activated
C14 H21 Na O13
ZUL-520 methanol solvate
MIL89 Lutidine
cefminox sodium heptahydrate
CoV- BCP-TPT-Bz
F-MOF 2
F-MOF 3
F-MOF 4
F-MOF 5
PCN-224Co(ii) plus CO
PCN-224Co(ii) plus CO
PCN-224Co(ii) plus CO
PCN-224Co(ii) plus CO
JLU-Liu 33
COV-1 CdS-TMDPY
COV-2 CdS-TMDPy-TPhP
COV-3 CdS-BPy
COV-4 CdS-TMDPy
COV-3 CdSeS-BPy
AlFFIVE-1-Ni (KAUST-8) dehydrated
AlFFIVE-1-Ni (KAUST-8) rehydrated
AlFFIVE-1-Ni (KAUST-8) as-synthesised
AlFFIVE-1-Ni (KAUST-8) CO2
bis(Cimetidine)-copper(ii) dinitrate
MFM-115a pentakis(deuteromethane) clathrate
MFM-115a nonakis(deuteromethane) clathrate
MFM-132a bis(deuteromethane) clathrate
MFM-132a tris(deuteromethane) clathrate
MFM-300(Cr) sulfuric acid hydrate
CAU-37 as synthesised
CAU-37 activated
CAU-37 activated
Anhydrous zinc(ii) heptanoate
PCM-101 (partially oxidized)
MFM-808 unknown solvate
Cu-ADA-253 unknown solvate
NKU-999-Tb p-xylene
NKU-999-Dy p-xylene
ZIF-2 N,N-dimethylformamide solvate
ZIF-60 N,N-dimethylformamide solvate
ZIF-GIS-Im/mIm N,N-diethylformamide solvate
Zn(Im)1.92(1)(mIm)0.08(1) N,N-dimethylformamide solvate
ZIF-GME-Im/mIm N,N-diethylformamide solvate
Zn(Im)1.92(1)(mIm)0.08(1) dodecahydrate
Zn(Im)1.92(1)(mIm)0.08(1) 1,2-ethanediol solvate
ZIF-60 ethanol solvate
Zn(Im)1.92(1)(mIm)0.08(1) ethanol solvate
Zn(Im)1.84(3)(mIm)0.16(3) methanol solvate
Zn(Im)1.84(3)(mIm)0.16(3) methanol solvate
Zn(Im)1.84(3)(mIm)0.16(3) methanol solvate
Zn(Im)1.87(2)(mIm)0.13(2) N,N-diethylformamide solvate
Zn(Im)1.87(2)(mIm)0.13(2) N,N-diethylformamide solvate
Zn(Im)1.87(2)(mIm)0.13(2) N,N-diethylformamide solvate
Zn(Im)1.87(2)(mIm)0.13(2) N,N-diethylformamide solvate
Zn(Im)1.87(2)(mIm)0.13(2) N,N-diethylformamide solvate
Zn(Im)1.87(2)(mIm)0.13(2) N,N-diethylformamide solvate
ZIF-60-non-stoichiometric N,N-diethylformamide solvate
Zn(Im)1.87(2)(mIm)0.13(2) N,N-diethylformamide solvate
Zn(Im)1.84(3)(mIm)0.16(3) N,N-diethylformamide solvate
Zn(Im)1.84(3)(mIm)0.16(3) methanol solvate
IITKGP-40 unknown solvate
Bionectriol D
Hydrated SJTU-9-pyrazine
the activated NJU-Bai62
Silver pefloxacin trihydrate
CUST-555 unknown solvate
di-sodium pamidronate pentahydrate
activated ZUL-C1
MIL-53 mη-xylene
MIL-53 ortho-cymene
MIL-53as p-xylene
MIL-53ht p-xylene
Fenoprofen calcium
MIL-53 ortho-xylene
Lithium benzilate hemihydrate
MUF-16 (Mn)
ZIF-8 n-butanol, ZIF-8
UiO-66-NH3+ ReO4
MST-2 (Co-Zn)
Th-SINAP-2 4-([12,22:26,32-terpyridin]-24-yl)benzoic acid
MFM-188a desolvated
NKU-100 activated
NKU-100 regenerated
Sodium sulfacetamide monohydrate
Co(4-DPDS)2MoO4 as-synthesised
Co(4-DPDS)2MoO activated
ZU-609 propylene solvate
PUM168 N,N-dimethylformamide diethyl ether solvate
Potassium carminate trihydrate
ZNU-10 octahydrate
ZNU-10 N,N-dimethylformamide solvate
Cu-DCB-MOF unknown solvate
SJTU-9 hydrate
Zinc pyromellitate heptahydrate
HKUST-1 (as synthesised)
HKUST-1 (degassed)
LIFM-DSL-1 L
CORN-MOF-1 (Ni)
CORN-MOF-1 (Mg)
UiO-67 Au(iii)
In-MOF 1
HKUST-1 unknown solvate
JLU-Liu 34
DUT-98 as made
DUT-98 close pore
Mn-CUK-1 (273 K)
Mn-CUK-1 (100 K)
Mn-CUK-1 (313 K)
NU-1000-SO4 dichloromethane solvate
NU-1000-SO4-130 deg.C
NU-1000-SO4 dihydrate
NU-1000-SO4 dihydrate
CCIQS-1 tetrahydrofuran solvate
CCIQS-1 methanol solvate
CCIQS-1 acetone solvate
NTU-88 bis(propyne)
MFM-132a+1.0 D2
MFM-132a+0.5 D2
CdIF-13 propane
CdIF-13 propane
CdIF-13 propane
Eu-TZB-MOF unknown solvate
Eu-TZB-MOF / Tb-TZB-MOF  unknown solvate
Mn-BDC-TPA unknown solvate
CALF-35 (Ce)
Cobalt dicyanamide
Y-shp-MOF-5 (0% RH)
Y-shp-MOF-5 22% humidity
Y-shp-MOF-5 100% humidity
PCN-606-NH2 (fresh)
PCN-606-OH (fresh)
PCN-606-OMe (fresh)
MFM-300(Fe) benzene clathrate hydrate
MFM-300(Cr) benzene clathrate hydrate
MFM-300(In) benzene clathrate monohydrate
MFM-300(Fe) cyclohexane clathrate hydrate
UiO-66 benzene clathrate
UiO-66-defect-Cu(i) benzene clathrate
UiO-66-defect-Cu(ii) benzene clathrate
UiO-66-defect benzene clathrate
UiO-66 cyclohexane clathrate
UiO-66-defect-Cu(i) cyclohexane clathrate
UiO-66-defect-Cu(ii) cyclohexane clathrate
UiO-66-defect cyclohexane clathrate
[2]-bis(bis(μ-2,2'-{1,4-phenylenebis[(2H-pyrrol-2-ylidene)methylene]}bis(1H-pyrrole))-bis(μ-1,1'-(1,4-phenylene)bis(1H-imidazole))-)-catenane hexakis(trifluoromethanesulfonate)
KAUST-7 (sulfur dioxide)
KAUST-8 (sulfur dioxide)
Paliotol Yellow K2270
α-Pigment Yellow 191
β-Pigment Yellow 191
MIL-96 (Ga)
sodium lithol red monohydrate
β-Pigment yellow 183
Pigment yellow 183 dimethylformamide solvate
Pigment yellow 191 dimethylformamide solvate
NU-1501-Fe-water treated
mDESY-1 azobenzene
[2]-bis[(μ-2,3-bis(4,4',4''-{1,3,5-triazine-2,4,6-triyltris[(4,1-phenylene)thiene-5,2-diyl]}tris(phenyl))-tris(1,4-bis[butyl(dimethyl)silyl]-buta-1,3-diene-1,4-diyl))-hexakis(cyclopentadienyl)-tri-zirconium(iv)]-perplexane unknown solvate
C36 H30 N3 O9 Tb
Hf-MOF-808 selenate unknown solvate
Hf-MOF-808 selenite unknown solvate
fluconazole pentahydrate
sodium (1S)-D-lyxit-1-yl­sulfonate
as-synthesized bMOF-200
Pigment Red 53:2
NOTT-210 dimethylformamide solvate tetrahydrate
NOTT-211 dimethylformamide solvate dihydrate
NOTT-212 dimethylformamide solvate tetrahydrate
NOTT-213 dimethylformamide solvate dihydrate
MOF-5(C7)_desolvated phase
C24 H20 N2 Ni O5 S2
Glibenclamide potassium salt
Glibenclamide sodium salt
Glibenclamide sodium salt
Glibenclamide sodium salt hydrate
DZU-101 unknown solvate
DZU-102 unknown solvate
bismuth sub-gallate dihydrate
Cesium 5-oxotetrazolate
Activated NTUniv-56
as synthesized NTUniv-56
silver dinitramide
NU-1000 perrhenate unknown solvate
NTU-72 tetrahydrate
Sodium theophyllinate monohydrate
JXUST-301 N,N-dimethylformamide solvate pentahydrate
Al-CAU-13 hydrate
Al-CAU-13 hydrate
Al-CAU-13 hydrate
Al-CAU-13 hydrate
Th-SINAP-24 unknown solvate
Cu-MOF 1
MIL-96 (Al)
potassium hydrogen pthalate
BTB-MOF-24 tegafur
BTB-MOF-24 1,12-dibromododecane
BTB-MOF-24 tetraglyme methanol solvate
BTB-MOF-24 squalene
BTB-MOF-24 methyl oleate
BTB-MOF-24 methyl oleate
BTB-MOF-24 methyl linoleate
BTB-MOF-24 methyl linoleate
BTB-MOF-24 methyl linolenoate
BTB-MOF-24 methyl linolenoate
BTB-MOF-24 farnesol
BTB-MOF-24 DHA ethyl ester
BTB-MOF-24 oleic acid
BTB-MOF-24 citronellal
BTB-MOF-24 ricinoleate
BTB-MOF-24 citronellal
hcp UiO-66(Zr)
ZUL-500 activated
CoMOF-1 N,N-dimethylformamide methanol solvate dihydrate
Rochelle salt
Rochelle salt
Rochelle Salt
Rochelle Salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
Rochelle salt
NTUniv-80 unknown solvate
KMF-1 dehydrated
KMF-1 hydrated
Potassium violurate dihydrate
Liu-4_cinnamic (close pore phase)
UAM-1, catena-[tetrakis(μ-bis(4-carboxylatopyrazol-1-yl)methane)-tetrakis(μ-hydroxo)-tetrakis(μ-oxido)-tetrakis(formato)-tetra-zirconium(iv) N,N-dimethylformamide solvate]
sodium nicotinate
Lithium hydrogen squarate monohydrate
NKU-111 anthracene
sodium elsulfavirine
sodium elsulfavirine
ELM-11 bis(n-butane)
MIL-68 (In)
MIL-68 (Ga)
ZU-601 unknown solvate
ZU-602 but-2-ene unknown solvate
ZU-601 activated
ZU-602 unknown solvate
ZU-602 activated
MIL-53 deuterium
MIL-53 deuterium
CID-3 dimethylformamide clathrate
NU-1000-FF-Cu-SIM unknown solvate
75-DGIST-4 (0.12 min)
75-DGIST-4 (0.36 min)
75-DGIST-4 (0.48 min)
75-DGIST-4 (1.17 min)
75-DGIST-4 (1.79 min)
75-DGIST-4 (7.91 min)
75-DGIST-4 (23.15 min)
75-DGIST-4 (35.27 min)
75-DGIST-4 (125.56 min)
75-DGIST-4 (845.68 min)
MOF-5 heptakis(ferrocene) clathrate
JXNU-12 unknown solvate
JXNU-12(F) unknown solvate
Ni-CPO-27 CO loaded
magnesium stearate trihydrate
BIF-90 unknown solvate
α-ZIF-65 unknown solvate
α-ZIF-65 unknown solvate
β-ZIF-65 unknown solvate
β-ZIF-65 unknown solvate
sodium letermovir
solvent-loaded ZU-72
activated ZU-72
nHEX-loaded ZU-72
reactivated nHEX loaded ZU-72
BUT-233 unknown solvate
Phaseolide A
Imidazole-doped MOF-217
UPC-48 N,N-dimethylformamide solvate sesquihydrate
MUF-15-F methanol solvate
MUF-15-CH3 methanol solvate
UOW-7 3DED
Sodium acetate trihydrate
Ferric train
1740 Cu3(CN)3(qbtz)2
amino-MIL53(Al) LP form
amino-MIL53(Al) NP form
amino-MIL53(Al) close form
ZU-33 hemikis(acetylene) unknown solvate
activated COK-18
C12 H8 Cu N2 O4
CAU-15-Cit Hydrated
CAU-15-Cit Anhydrous
UPC-66 as synthesised
UPC-66 as synthesised
UPC-66 Activated
UPC-66 Activated
UPC-66 Activated
UPC-66 Activated
UPC-66 Activated
UPC-66 Activated
UPC-66 Solvent exchanged
ZIF-8 unknown solvate
ZIF-8 6.32Ar
ZIF-8 8.27methane
ZIF-8 5.5Ar
ZIF-8 9.76methane
ZIF-8 3.25methane
ZIF-8 4.22dinitrogen
ZIF-8 4.44dinitrogen
ZIF-8 5.63dinitrogen
ZIF-8 6.21dinitrogen
ZIF-8 5.9Ar
ZIF-8 6.23dinitrogen
ZIF-8 6.29dinitrogen
ZIF-8 5.5dinitrogen
ZIF-8 10.08methane
ZIF-8 6.06dioxygen
ZIF-8 6.18dioxygen
ZIF-8 8.16dioxygen, ZIF-8
ZIF-8 5.5dioxygen
ZIF-8 8.40dioxygen
ZIF-8 8.25dinitrogen
ZIF-8 5.5methane
ZIF-8 4.08methane
C24 H16 N2 O4 Pb
PCN-81 tetradeuteromethane
PCN-81 tetradeuteromethane
PCN-81 tetradeuteromethane
BIPT-1 N,N-dimethylformamide solvate trihydrate
CdIF-13 propylene
CdIF-13 propylene
CdIF-13 propylene
CdIF-13 propylene
maned dihydrate
HU13-R unknown solvate
pemetrexed disodium heptahydrate
IITKGP-53 aniline
ZIF-8 hydrate
PCN-514-DMA complex
Tribenzylstannyl 4-(2-methoxyphenylamino)-4-oxobutanoate
Mg-CUK-1 nonahydrate
Mg-CUK-1 benzene solvate
Mg-CUK-1 pyridine solvate
Mg-CUK-1 benzyl alcohol solvate
Mg-CUK-1 toluene solvate
Mg-CUK-1 p-xylene solvate
Mg-CUK-1 p-xylene solvate
Mg-CUK-1 p-divinylbenzene solvate
ELM-22 (Co)
PCN-514 (DMA)
qtz ZIF-8
WYU-61a benzene solvate
WYU-61a toluene solvate
WYU-61a m-xylene solvate
WYU-61a p-xylene solvate
WYU-61a o-xylene solvate
SBMOF-1 ethylene
SBMOF-2 ethylene
bis(μ-3,6-di(pyridin-4-yl)-9-[4-(pyridin-4-yl)phenyl]-9H-carbazole)-tris(μ-3,6-dioxocyclohexa-1,4-diene-1,4-bis(olato))-hexakis(pentamethylcyclopentadienyl)-hexa-rhodium hexakis(trifluoromethanesulfonate) methanol solvate
TMU-5 (Cd 15%)
TMU-5 (Cd 30%)
NJU-Bai 17
PUM-168 eugenol thymol N,N-dimethylformamide solvate
PUM-168 eugenol thymol N,N-dimethylformamide solvate
PUM-168 eugenol thymol N,N-dimethylformamide solvate
PUM-168 eugenol thymol N,N-dimethylformamide solvate
PUM-168  N,N-dimethylformamide solvate
PUM168 bis(eugenol) (carvacrol) guest N,N-dimethylformamide unknown solvate
PUM168 (thymol) guest N,N-dimethylformamide unknown solvate
PUM168 eugenol thymol N,N-dimethylformamide solvate
PUM168 tris(eugenol) bis(thymol) guest N,N-dimethylformamide solvate
PUM168 (eugenol) (carvacrol) guest N,N-dimethylformamide unknown solvate
HKUST-1 tetrakis(acetonitrile)-copper(i)
CAU-10-H Hydrated
CAU-10-H dry
JNU-200 (as synthesized)
JNU-200 (ethanol
exchanged)
Δ-MOF-520 benzoate N,N-dimethylformamide solvate
Δ-MOF-520 3-hydroxybenzoate unknown solvate
Δ-MOF-520 (-)-jasmonic acid unknown solvate
Δ-MOF-520 Genistein unknown solvate
Δ-MOF-520 diclofenac unknown solvate
Δ-MOF-520 ethylene glycolate unknown solvate
Δ-MOF-520 unknown solvate
Λ-MOF-520 3-nitrophenolate unknown solvate
Λ-MOF-520 Gibberellin A3 unknown solvate
Λ-MOF-520 trimesate unknown solvate
Λ-MOF-520 heptanoate unknown solvate
Λ-MOF-520 3-(t-butoxycarbonylamino)propan-1,2-diolato unknown solvate
Λ-MOF-520 Gibberellin A1 unknown solvate
Λ-MOF-520 unknown solvate
Λ-MOF-520 methanolate unknown solvate
Λ-MOF-520 4-bromophenolate unknown solvate
Λ-MOF-520 3,5-diaminobenzoate unknown solvate
Λ-MOF-520 (+)-jasmonic acid unknown solvate
AMU3 acetonitrile solvate
AMU3 acetonitrile solvate
AMU3 acetonitrile solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 N,N-dimethylformamide solvate
AMU3 acetonitrile solvate
AMU3 acetonitrile solvate
AMU3 acetonitrile solvate
ZSTU-10 N,N-dimethylformamide solvate
MFM-300(In) 1.09CD4 per In
MFM-300(In) 2.09CD4 per In
MFM-300(In) 3.11CD4 per In
MFM-300(In) 0.90D2
MFM-300 (In) 1.60 D2
MFM-300 (In) 2.99 D2
MFM-300 (In) 4.83 D2
MFM-300 (In) 6.08 D2
NbOFFIVE-1-Ni CO2
sodium quercetin-5'-sulphonate tetrahydrate
sodium quercetin-5'-sulphonate acetone solvate
MOF MRT-3
potassium t-butyl 5-butyl-3-oxo-4-(trifluoroboranyl)-3,6-dihydropyridine-1(2H)-carboxylate
n-butane@DUT-149 (loading 7)
Ni-CPO-27 SO2 loaded
Ni-MOF-74 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-MOF-74 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-CPO-27 SO2 loaded
Ni-MOF-74 SO2 loaded
IRMOF-(TF)3(TDA-EtOH)17 unknown solvate
IRMOF-(CH2N3)20 N,N-diethylformamide solvate
IRMOF-(TF)20-R1 unknown solvate
CUST-562 unknown solvate
DUT-193 MOF
Sodium tetrabetaine-copper(ii) triperchlorate
DO-MOF dimethylformamide solvate
Copper dicyanamide
Copper dicyanamide
Copper dicyanamide
hemikis(Cobaltocene) MIL-47(V)
(2)-bis(bis(μ2-Cyclohexylidenebis(3-(p-phenylenoxy)propynyl))-bis(1,4-bis(diphenylphosphino)butane)-tetra-gold(i))-catenane dichloromethane solvate heptahydrate
ZU-61 p-xylene
ZU-61 o-xylene
U-MOF-L2 unknown solvate
U-MOF-L1 unknown solvate
U-MOF-L3 unknown solvate
U-MOF-L4 unknown solvate
U-MOF-L5 unknown solvate
IRMOF-(TF)20 unknown solvate
MIL-88B N,N-dimethylformamide solvate
NU-2011 N,N-dimethylformamide solvate
NU-2011 N,N-dimethylformamide solvate
NU-2010 acetonitrile solvate
NU-2010 acetonitrile solvate
NU-2010 N,N-dimethylformamide solvate
NU-2010 1,4-dioxane solvate
NU-2010 hydrate
NU-2010 methanol solvate
bis(MIL-53(Al)) ferrocene clathrate
tris(MIL-53(Al)) 1-ferrocenealdehyde clathrate
WSU-10(Cu) N,N-dimethylformamide solvate
WSU-11(Cu) unknown solvate
WSU-11(Zn) N,N-dimethylformamide solvate
WSU-20(Co) dihydrate N,N-dimethylacetamide solvate
WSU-20(Zn) N,N-dimethylacetamide solvate
WSU-12(Cu) N,N-dimethylformamide solvate
Lithium benzimidazolate
α-Sodium benzimidazolate
β-Sodium benzimidazolate
as synthesized MOF-14
evacuated MOF-14
AlFFIVE-1-Ni (hydrogen sulfide)
AlFFIVE-1-Ni (carbon dioxide)
Λ-MOF-520-29 unknown solvate
Δ-MOF-520 N,N-dimethylformamide solvate
di-potassium chloranilate monohydrate
Mg-CUK-1L Dehydrated
Mg-CUK-1L incl. o-Xylene
Mg-CUK-1L incl. AzB
MFM-300(In) P8
MFM-300(In) P8
BUT-64 hydrate unknown solvate
BUT-64 N,N-dimethylformamide solvate hydrate unknown solvate
BUT-64 hydrate acetone unknown solvate
BUT-64 N,N-dimethylformamide unknown solvate
BUT-64 N,N-dimethylformamide acetonitrile unknown solvate
ammonia BUT-64 hydrate
β-zinc formate
KAUST-7 propylene
KAUST-7 propane
OX-loaded ZUL-C3
activated ZUL-C3
as-synthesized ZUL-C3
PX-loaded ZUL-C3
water-adsorbed FDC–1a
water-adsorbed FDC–2a
NKMOF-14-PZ C2H6
NKMOF-14-PZ C2H4
NKMOF-14-PD C2H6
NKMOF-14-PD C2H4
NKMOF-14-PZ (evacuated)
NKMOF-14-PD (evacuated)
FJI-H36 bis(acetylene)
Calcium valproate dihydrate
NKU-200-Eu tetrahydrofuran solvate
NKU-200-Eu tetrahydrofuran solvate
D-ZIF-7 CO2
D-ZIF-7 CO2
D-ZIF-7 CO2
NUC-61 Dy
NUC-61 Ho
Zn-ETTOB unknown solvate
MFM-300(Cr) 4-methoxybenzaldehyde
MFM-300(Cr) acetophenone hydrate
MFM-300(Cr) [1,1'-biphenyl]-4-carbaldehyde
MFM-300(Cr) benzaldehyde
TYUT-15 unknown solvate
UiO-66 synthesised in formic acid:DEF 0.5:1
UiO-66 synthesised in formic acid:DEF 0.75:1
UiO-66 synthesised in formic acid:DEF 1:1
UiO-66 synthesised in formic acid:DEF 2:1
UiO-66 activated 300C then rehydrated
UiO-66 synthesized from ZrBr4 salt
EHU-30, UiO-66
DZU-17 unknown solvate
PCN-9 (Fe)
PCN-9 (Mn)
Copper sodium Tritartrate
MnMOF‐1 methanol solvate
MnMOF‐1 p‐xylene solvate
MnMOF‐1 diethyl ether solvate
MnMOF‐1 ethanol solvate
MnMOF‐1 dichloromethane solvate
MnMOF‐1 acetone solvate
MnMOF‐1 tetrahydrofuran solvate
BOB MOF
BOP MOF
DUT-8(Ni) ip2
HIAM-201 o-xylene
HIAM-201 p-xylene
HIAM-201 m-xylene
ELM-12 perdeuteroprop-1-yne
guest-free ZnCID-24
dodecakis(acetonitrile-aqua)-CPF-5 unknown solvate trihydrate
dodecakis(acetonitrile-(2-aminothiazole))-CPF-5 unknown solvate tetrahydrate
octakis(3-aminopyridine)-CPF-5 unknown solvate dihydrate
octakis(4-(3-(pyridin-4-yl)propyl)pyridine)-CPF-5 unknown solvate dihydrate
CPF-5 tris(1-aminoadamantane) unknown solvate
tetrakis(1,4,7-tris(prop-1-yn-3-yl)-1,4,7-triazacyclononane)-CPF-5 unknown solvate monohydrate
tetrakis(pyridine)-octa-aqua-CPF-5 unknown solvate tetrahydrate
tetrakis(1,4,7-triazacyclononane)-CPF-5 acetonitrile unknown solvate dihydrate
PCN-9 (Co)
MIL-53(Fe) m-xylene clathrate
MIL-53(Fe) o-xylene clathrate
MIL-53(Fe) p-xylene clathrate
MIL-53(Fe) p-xylene clathrate
Mono-sodium glutamate monohydrate
UPC-22 unknown solvate
Di-lithium dihydrogen pyromellitate tetrahydrate
MAF-23 hemikis(propylene)
MAF-23 hemikis(propane)
MAF-23-O hemikis(propylene)
MAF-23-O hemikis(propane)
YCM-32 spPPCl
YCM-32 TEACl
YCM-31 spPPCl
YCM-31 spMPBr
PFC-8-Aqua regia
PMOF-55 sesquikis(carbon dioxide) dihydrate
NH2-PMOF-55 sesquikis(carbon disulfide) dihydrate
p-sulfonato-calix[4]arene tris(benzamidinium) hydate
UiO-66 environment cell stage 1
UiO-66 environment cell stage 4
UiO-66 synthesised in formic acid:DEF 1.25:1
dehydroxylated UiO-66
UiO-66 propoxide
UiO-66 propoxide activated 150C
UiO-66 propoxide activated 300C
desolvated UZAR-S12
MFM-300(Ga2) N,N-dimethylformamide solvate tetrahydrate
sodium alendronate trihydrate
NJU-Bai 41
NJU-Bai 43
Al-MIL53 hydrate
BBPA-Ca form II
NU-1000-MoSx-SIM unknown solvate
NU-1000-MoOx-SIM unknown solvate
PUM168 bis(eugenol) guest N,N-dimethylformamide solvate
PUM168 N,N-dimethylformamide solvate
PUM168 N,N-dimethylformamide acetone solvate
PUM168 tris(eugenol) guest
PUM168 tris(eugenol) guest
CD-MOF-1 hydrate
CD-MOF-1 eugenol clathrate  hydrate
Gd-RUM1 N,N-dimethylformamide solvate dihydrate
Eu-RUM1 bis(methanol) clathrate hydrate
Gd-RUM1  hemikis(2,6-dimethylanaline) clathrate N,N-dimethylformamide unknown solvate
Gd-RUM1 bis(pyridine) clathrate monohydrate
Gd-RUM1 chloroform clathrate unknown solvate dihydrate
Gd-RUM2 N,N-dimethylformamide solvate hydrate
Gd-RUM2 hemikis(methanol) clathrate N,N-dimethylformamide solvate
Gd-RUM2 bis(pyridine) clathrate unknown solvate
Gd-RUM2 hemikis(carvone) clathrate N,N-dimethylformamide solvate

In [12]:
# Check papers with a lot of entries
doi_note = {
    "10.1002/cssc.201601752": "in-situ study of M-MOF-74",
}

for doi, note in doi_note.items():
    df_doi = df[df['publication_doi']==doi]
    print(doi, f"({note})", f"Number of CIFs: {len(df_doi)}", 'Synonyms:', *list(set(df_doi['synonyms'])))

10.1002/cssc.201601752 (in-situ study of M-MOF-74) Number of CIFs: 1853 Synonyms: ['CPO-27-Mn'] ['CPO-27-Co'] ['CPO-27-Cu'] ['CPO-27-Zn'] ['CPO-27-Mg'] ['CPO-27-Ni'] []

In [13]:
# Keep only 3 MOFs for the same DOI with the same synonyms, to avoid having paper with hundreds of structures
df = pd.read_csv("data/step-01.csv")
df['note'] = "-" # Assign a string for all the notes, to make the later filtering easier
df = df.sort_values(by=['publication_doi','synonyms','identifier'])
df = df.reset_index() # keeping the old as column "index"

max_same = 3
count_same=0
for i in tqdm(df.index[1:]): # skipping the first because it is comparing with the previous (no privious for the first!)
    if df.at[i,'synonyms']!='[]':
        if df.at[i,'publication_doi']==df.at[i-1,'publication_doi'] and df.at[i,'synonyms']==df.at[i-1,'synonyms']:
            count_same+=1
        else:
            count_same=0
        if count_same>=3:
            df.at[i, 'note'] = f"Excluding more than {max_same} same MOFs from the same DOI"

df = df.sort_values(by='index')
df = df.drop(columns='index') # remove the dummy column
df.to_csv("data/step-02.csv", index=False)
# step-02.csv: contains a "note" for excluding structures if >3 from the same paper

100%|██████████| 135252/135252 [00:01<00:00, 127828.32it/s]

In [14]:
df = pd.read_csv("data/step-02.csv")
len_after_exclusions = len(df[(df['synonyms']!="[]") & (df['note']=='-')])
print("CSD entries having synonyms:", len_after_exclusions, f"(including only {max_same} same materials per paper)")

CSD entries having synonyms: 7043 (including only 3 same materials per paper)

In [15]:
df = pd.read_csv("data/step-02.csv")
df[df['synonyms']!="[]"].head(3)

,identifier,ccdc_number,formula,has_disorder,publication_year,publication_doi,synonyms_orig,synonyms,note
13,ABAVIM01,1984147,"(C24 H26 N3 Ni1 O11 P3)n,H2 O1",True,2021,10.1007/s12274-020-3056-6,['IEF-13'],['IEF-13'],-
37,ABECIX,2081306,(C52 H34 Ag1 Co3 F1 N2 O13 P2)n,True,2021,10.1021/jacs.1c05564,['Ag-PCM-102'],['Ag-PCM-102'],-
38,ABECOD,2081307,"0.71(C55 H43 Ag1 Co3 F1 N3 O15 P2)n,0.29(C55 H...",True,2021,10.1021/jacs.1c05564,['AgCu-PCM-102'],['AgCu-PCM-102'],-